apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookkin
  name: bookkin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookkin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bookkin
    spec:
      containers:
        - image: gcr.io/iacotrane-bookkin/github.com/iacotrane/bookkin:latest
          imagePullPolicy: Always
          name: bookkin
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: bookkin
  name: bookkin
  namespace: default
spec:
  clusterIP: 10.3.253.62
  externalTrafficPolicy: Cluster
  ports:
    - name: 8080-8080
      nodePort: 30808
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: bookkin
  sessionAffinity: None
  type: LoadBalancer
